/**
 * Comprehensive allergen mapping with common ingredient variations and synonyms
 * Used for detecting allergens in ingredient lists without requiring AI API calls
 */

export type AllergenKeywordMap = {
  [allergen: string]: string[];
};

export const allergenKeywordMapping: AllergenKeywordMap = {
  peanuts: [
    "nut",
    "nuts",
    "peanut",
    "peanuts",
    "groundnut",
    "groundnuts",
    "ground nut",
    "ground nuts",
    "goober",
    "goober peas",
    "monkey nut",
    "monkey nuts",
    "earth nut",
    "earth nuts",
    "peanut butter",
    "peanut oil",
    "peanut flour",
    "peanut protein",
    "peanut paste",
    "peanut sauce",
    "arachis oil",
    "arachis hypogaea",
    "arachide",
    "cacahuete",
    "cacahuate",
    "mandelona",
    "nut pieces",
    "chopped nuts",
    "crushed peanuts",
    "roasted peanuts",
    "salted peanuts",
    "honey roasted peanuts",
    "beer nuts",
    "mixed nuts",
    "trail mix",
    "satay",
    "goobers",
    "nu-nuts",
    "nut meat",
    "peanut extract",
  ],

  milk: [
    "milk",
    "dairy",
    "cream",
    "creamer",
    "heavy cream",
    "light cream",
    "whipping cream",
    "double cream",
    "single cream",
    "clotted cream",
    "butter",
    "buttermilk",
    "cultured buttermilk",
    "cheese",
    "cottage cheese",
    "cream cheese",
    "soft cheese",
    "hard cheese",
    "processed cheese",
    "cheese food",
    "cheese product",
    "cheese sauce",
    "cheese powder",
    "yogurt",
    "yoghurt",
    "greek yogurt",
    "frozen yogurt",
    "yogurt powder",
    "ghee",
    "clarified butter",
    "whey",
    "whey protein",
    "whey powder",
    "sweet whey",
    "acid whey",
    "demineralized whey",
    "casein",
    "caseinate",
    "sodium caseinate",
    "calcium caseinate",
    "potassium caseinate",
    "casein hydrolysate",
    "lactose",
    "lactalbumin",
    "lactoglobulin",
    "lactoferrin",
    "lactoserum",
    "curds",
    "custard",
    "pudding",
    "milk pudding",
    "half and half",
    "half & half",
    "sour cream",
    "condensed milk",
    "sweetened condensed milk",
    "evaporated milk",
    "powdered milk",
    "milk powder",
    "dried milk",
    "dry milk solids",
    "whole milk",
    "whole milk powder",
    "skim milk",
    "skimmed milk",
    "nonfat milk",
    "fat-free milk",
    "low-fat milk",
    "reduced-fat milk",
    "2% milk",
    "1% milk",
    "malted milk",
    "milk solids",
    "nonfat milk solids",
    "milk protein",
    "milk protein concentrate",
    "milk protein isolate",
    "milk fat",
    "milk fat globules",
    "butterfat",
    "anhydrous milk fat",
    "butter oil",
    "rennet",
    "rennet casein",
    "recaldent",
    "simplesse",
    "queso",
    "queso fresco",
    "paneer",
    "ricotta",
    "mozzarella",
    "cheddar",
    "parmesan",
    "parmigiano",
    "swiss cheese",
    "gouda",
    "brie",
    "camembert",
    "feta",
    "blue cheese",
    "gorgonzola",
    "kefir",
    "kumiss",
    "koumiss",
    "ice cream",
    "ice milk",
    "gelato",
    "sherbet",
    "frozen custard",
    "dulce de leche",
    "caramel",
    "toffee",
    "butterscotch",
    "nougat",
    "dairy creamer",
    "coffee creamer",
    "non-dairy creamer", // may contain milk derivatives
    "artificial butter flavor",
    "butter flavor",
    "milk chocolate",
    "white chocolate",
  ],

  eggs: [
    "egg",
    "eggs",
    "whole egg",
    "whole eggs",
    "egg white",
    "egg whites",
    "egg yolk",
    "egg yolks",
    "egg powder",
    "powdered eggs",
    "dried egg",
    "dried eggs",
    "dehydrated eggs",
    "liquid eggs",
    "frozen eggs",
    "pasteurized eggs",
    "egg product",
    "egg solids",
    "egg protein",
    "albumin",
    "albumen",
    "ovalbumin",
    "ovomucin",
    "ovomucoid",
    "ovotransferrin",
    "ovovitellin",
    "vitellin",
    "globulin",
    "livetin",
    "lysozyme",
    "egg lecithin",
    "apovitellin",
    "egg substitutes", // may contain egg
    "egg replacer",
    "egg wash",
    "mayonnaise",
    "mayo",
    "aioli",
    "meringue",
    "meringue powder",
    "surimi",
    "eggnog",
    "egg nog",
    "hollandaise",
    "bearnaise",
    "caesar dressing",
    "egg pasta",
    "egg noodles",
    "pasta", // often contains eggs
    "fresh pasta",
    "lecithin", // can be egg-derived
    "simplesse",
    "binder",
    "egg binder",
    "custard",
    "flan",
    "quiche",
    "frittata",
    "omelet",
    "omelette",
    "souffle",
    "zabaglione",
    "marshmallow",
    "marzipan",
    "nougat",
    "macarons",
  ],

  soy: [
    "soy",
    "soya",
    "soybean",
    "soybeans",
    "soy bean",
    "soy beans",
    "soya bean",
    "soja",
    "glycine max",
    "edamame",
    "tofu",
    "bean curd",
    "tempeh",
    "miso",
    "miso paste",
    "natto",
    "shoyu",
    "tamari",
    "soy sauce",
    "soya sauce",
    "light soy sauce",
    "dark soy sauce",
    "soy milk",
    "soya milk",
    "soy beverage",
    "soy drink",
    "soy protein",
    "soy protein isolate",
    "soy protein concentrate",
    "hydrolyzed soy protein",
    "textured soy protein",
    "soy flour",
    "soy lecithin",
    "soy oil",
    "soybean oil",
    "soya oil",
    "vegetable oil", // often soybean
    "textured vegetable protein",
    "tvp",
    "tsp",
    "soy albumin",
    "soy fiber",
    "soy grits",
    "soy nuts",
    "soy sprouts",
    "bean sprouts", // may be soy
    "yuba",
    "tofu skin",
    "okara",
    "soy pulp",
    "kinako",
    "soybean flour",
    "teriyaki",
    "teriyaki sauce",
    "hoisin",
    "hoisin sauce",
    "oyster sauce", // may contain soy
    "vegetable protein",
    "vegetable gum",
    "vegetable broth", // may contain soy
    "vegetable stock",
    "hydrolyzed vegetable protein",
    "hvp",
    "mono-diglyceride",
    "monoglyceride",
    "diglyceride",
    "soy isoflavones",
    "soy peptides",
    "soy polysaccharides",
    "miso soup",
    "soy cheese",
    "soy yogurt",
    "soy ice cream",
    "soy butter",
    "soy margarine",
  ],

  wheat: [
    "wheat",
    "wheat flour",
    "whole wheat",
    "whole grain wheat",
    "refined wheat",
    "wheat bran",
    "wheat germ",
    "wheat starch",
    "wheat gluten",
    "wheat protein",
    "modified wheat starch",
    "gelatinized wheat starch",
    "pregelatinized wheat starch",
    "durum",
    "durum wheat",
    "hard wheat",
    "soft wheat",
    "red wheat",
    "white wheat",
    "semolina",
    "spelt",
    "kamut",
    "khorasan wheat",
    "farro",
    "einkorn",
    "emmer",
    "triticale",
    "bulgur",
    "bulgur wheat",
    "cracked wheat",
    "couscous",
    "pearl couscous",
    "israeli couscous",
    "seitan",
    "wheat meat",
    "bread",
    "wheat bread",
    "white bread",
    "sourdough",
    "baguette",
    "ciabatta",
    "focaccia",
    "pita",
    "naan",
    "tortilla", // flour tortillas
    "wrap",
    "flatbread",
    "breadsticks",
    "bread crumbs",
    "breadcrumbs",
    "panko",
    "croutons",
    "stuffing",
    "dressing",
    "pasta",
    "macaroni",
    "spaghetti",
    "linguine",
    "fettuccine",
    "penne",
    "rigatoni",
    "lasagna",
    "ravioli",
    "tortellini",
    "orzo",
    "noodles",
    "egg noodles",
    "ramen",
    "ramen noodles",
    "udon",
    "udon noodles",
    "soba", // often contains wheat
    "lo mein",
    "chow mein",
    "flour",
    "all-purpose flour",
    "enriched flour",
    "white flour",
    "wheat-based flour",
    "bread flour",
    "cake flour",
    "pastry flour",
    "self-rising flour",
    "self-raising flour",
    "graham flour",
    "whole wheat flour",
    "wheat meal",
    "bran",
    "wheat bran",
    "miller's bran",
    "cereal",
    "wheat cereal",
    "cereal extract",
    "cracker",
    "crackers",
    "cracker meal",
    "farina",
    "cream of wheat",
    "matzoh",
    "matzo",
    "matzah",
    "unleavened bread",
    "communion wafer",
    "vital wheat gluten",
    "hydrolyzed wheat protein",
    "wheat starch",
    "cookie",
    "cookies",
    "biscuit",
    "biscuits",
    "cake",
    "muffin",
    "pancake",
    "waffle",
    "pretzel",
    "bagel",
  ],

  fish: [
    "fish",
    "salmon",
    "atlantic salmon",
    "coho salmon",
    "sockeye salmon",
    "king salmon",
    "chinook salmon",
    "pink salmon",
    "smoked salmon",
    "lox",
    "gravlax",
    "tuna",
    "albacore",
    "yellowfin tuna",
    "bluefin tuna",
    "skipjack tuna",
    "canned tuna",
    "cod",
    "atlantic cod",
    "pacific cod",
    "black cod",
    "halibut",
    "pacific halibut",
    "haddock",
    "tilapia",
    "bass",
    "sea bass",
    "striped bass",
    "largemouth bass",
    "trout",
    "rainbow trout",
    "lake trout",
    "brook trout",
    "catfish",
    "mackerel",
    "king mackerel",
    "spanish mackerel",
    "sardine",
    "sardines",
    "pilchards",
    "anchovy",
    "anchovies",
    "anchoa",
    "herring",
    "pickled herring",
    "pollock",
    "alaska pollock",
    "walleye pollock",
    "snapper",
    "red snapper",
    "yellowtail snapper",
    "mahi mahi",
    "dorado",
    "dolphinfish",
    "swordfish",
    "grouper",
    "flounder",
    "sole",
    "dover sole",
    "petrale sole",
    "perch",
    "ocean perch",
    "pike",
    "northern pike",
    "walleye",
    "barramundi",
    "rockfish",
    "monkfish",
    "marlin",
    "wahoo",
    "caviar",
    "roe",
    "fish roe",
    "tobiko",
    "masago",
    "ikura",
    "fish eggs",
    "fish oil",
    "omega-3",
    "fish omega-3",
    "fish sauce",
    "fish stock",
    "fish broth",
    "fish bouillon",
    "fish paste",
    "fish extract",
    "worcestershire", // contains anchovies
    "worcestershire sauce",
    "caesar dressing", // often contains anchovies
    "puttanesca",
    "surimi",
    "imitation crab",
    "imitation seafood",
    "seafood flavoring",
    "fish gelatin",
    "fish protein",
    "fish hydrolysate",
    "dashi",
    "bonito",
    "katsuobushi",
    "fish cake",
    "kamaboko",
    "fish balls",
    "fish jerky",
    "dried fish",
    "salted fish",
    "fish powder",
  ],

  sesame: [
    "sesame",
    "sesame seed",
    "sesame seeds",
    "sesame oil",
    "toasted sesame oil",
    "sesame paste",
    "tahini",
    "tahina",
    "tehina",
    "tahin",
    "gomasio",
    "gomashio",
    "goma",
    "sesame salt",
    "benne",
    "benne seed",
    "benniseed",
    "sesamol",
    "sesamolin",
    "sesamum",
    "sesamum indicum",
    "til",
    "gingelly",
    "gingelly oil",
    "simsim",
    "sesame flour",
    "sesame protein",
    "halvah",
    "halva",
    "halawa",
    "hummus", // often contains tahini
    "houmous",
    "baba ganoush",
    "baba ghanoush",
    "za'atar",
    "zaatar",
    "dukkah",
    "duqqa",
    "sesame stick",
    "sesame cracker",
    "sesame snap",
    "sesame bar",
    "sesame candy",
    "sesame chicken",
    "sesame noodles",
    "everything bagel", // contains sesame
  ],

  sulfites: [
    "sulfite",
    "sulfites",
    "sulphite",
    "sulphites",
    "sulfur dioxide",
    "sulphur dioxide",
    "so2",
    "sodium sulfite",
    "sodium bisulfite",
    "sodium bisulphite",
    "sodium metabisulfite",
    "sodium metabisulphite",
    "potassium sulfite",
    "potassium bisulfite",
    "potassium bisulphite",
    "potassium metabisulfite",
    "potassium metabisulphite",
    "calcium sulfite",
    "calcium bisulfite",
    "e220",
    "e221",
    "e222",
    "e223",
    "e224",
    "e225",
    "e226",
    "e227",
    "e228",
    "dried fruit",
    "dried apricots",
    "raisins",
    "dried cranberries",
    "dried mango",
    "wine",
    "red wine",
    "white wine",
    "champagne",
    "sparkling wine",
    "sherry",
    "beer", // some contain sulfites
    "cider",
    "vinegar", // some types
    "balsamic vinegar",
    "wine vinegar",
  ],

  celery: [
    "celery",
    "celery seed",
    "celery seeds",
    "celery salt",
    "celery powder",
    "celery root",
    "celery knob",
    "celeriac",
    "celery stalk",
    "celery stalks",
    "celery leaves",
    "celery extract",
    "celery juice",
    "celery oil",
    "lovage",
    "leaf celery",
    "smallage",
    "wild celery",
    "apium",
    "apium graveolens",
    "celeriac puree",
  ],

  mustard: [
    "mustard",
    "mustard seed",
    "mustard seeds",
    "yellow mustard seed",
    "brown mustard seed",
    "black mustard seed",
    "white mustard seed",
    "mustard powder",
    "mustard flour",
    "mustard oil",
    "mustard paste",
    "yellow mustard",
    "dijon mustard",
    "brown mustard",
    "black mustard",
    "white mustard",
    "hot mustard",
    "chinese mustard",
    "english mustard",
    "whole grain mustard",
    "stone ground mustard",
    "honey mustard",
    "spicy mustard",
    "mustard greens",
    "mustard leaves",
    "mustard sauce",
    "mustard condiment",
    "brassica",
    "brassica nigra",
    "brassica juncea",
    "sinapis alba",
    "wasabi", // related to mustard family
    "japanese horseradish",
    "horseradish", // related to mustard family
    "prepared horseradish",
    "arugula", // mustard family
    "rocket",
    "watercress", // mustard family
    "radish", // mustard family
    "daikon",
    "turnip", // mustard family
    "rutabaga", // mustard family
    "rapeseed",
    "canola", // mustard family
  ],

  lupin: [
    "lupin",
    "lupine",
    "lupini",
    "lupin bean",
    "lupin beans",
    "lupini bean",
    "lupini beans",
    "lupin flour",
    "lupine flour",
    "lupin seeds",
    "lupin protein",
    "lupine protein",
    "lupinus",
    "lupinus albus",
    "altramuz",
    "termis",
    "tremoço",
  ],

  molluscs: [
    "mollusc",
    "molluscs",
    "mollusk",
    "mollusks",
    "shellfish",
    "clam",
    "clams",
    "littleneck clams",
    "cherrystone clams",
    "quahog",
    "manila clams",
    "razor clams",
    "geoduck",
    "steamer clams",
    "mussel",
    "mussels",
    "blue mussels",
    "green mussels",
    "oyster",
    "oysters",
    "pacific oysters",
    "kumamoto oysters",
    "bluepoint oysters",
    "scallop",
    "scallops",
    "bay scallops",
    "sea scallops",
    "squid",
    "calamari",
    "cuttlefish",
    "sepia",
    "octopus",
    "tako",
    "pulpo",
    "snail",
    "snails",
    "escargot",
    "abalone",
    "paua",
    "ormer",
    "conch",
    "periwinkle",
    "whelk",
    "cockle",
    "cockles",
    "sea snail",
    "limpet",
    "chiton",
  ],

  gluten: [
    "gluten",
    "wheat gluten",
    "vital wheat gluten",
    "wheat",
    "wheat flour",
    "wheat protein",
    "barley",
    "barley malt",
    "pearl barley",
    "hulled barley",
    "barley flour",
    "rye",
    "rye flour",
    "rye bread",
    "pumpernickel",
    "malt",
    "malt extract",
    "malt syrup",
    "malt flavoring",
    "malt vinegar",
    "malted barley",
    "malted wheat",
    "diastatic malt",
    "brewer's yeast",
    "nutritional yeast", // may be gluten-free
    "yeast extract",
    "spelt",
    "spelt flour",
    "kamut",
    "khorasan",
    "farro",
    "emmer",
    "einkorn",
    "durum",
    "semolina",
    "triticale",
    "seitan",
    "wheat meat",
    "bread",
    "pasta",
    "couscous",
    "bulgur",
    "beer", // contains gluten unless specified
    "ale",
    "lager",
    "stout",
    "porter",
    "soy sauce", // traditional contains wheat
    "shoyu",
    "teriyaki sauce",
    "flour tortilla",
    "flour",
    "breading",
    "batter",
    "hydrolyzed wheat protein",
    "modified food starch", // may contain gluten
    "dextrin", // may be from wheat
  ],

  lactose: [
    "lactose",
    "milk sugar",
    "milk",
    "dairy",
    "whey",
    "whey powder",
    "sweet whey",
    "cream",
    "buttermilk",
    "sour cream",
    "ice cream",
    "frozen yogurt",
    "yogurt",
    "yoghurt",
    "cheese",
    "soft cheese",
    "fresh cheese",
    "processed cheese",
    "butter",
    "milk powder",
    "dried milk",
    "milk solids",
    "nonfat dry milk",
    "condensed milk",
    "evaporated milk",
    "half and half",
    "coffee creamer",
    "dairy creamer",
  ],

  fructose: [
    "fructose",
    "fruit sugar",
    "levulose",
    "high fructose corn syrup",
    "hfcs",
    "corn syrup",
    "corn syrup solids",
    "glucose-fructose",
    "glucose-fructose syrup",
    "isoglucose",
    "agave",
    "agave nectar",
    "agave syrup",
    "blue agave",
    "honey",
    "raw honey",
    "apple",
    "apples",
    "apple juice",
    "apple sauce",
    "pear",
    "pears",
    "pear juice",
    "mango",
    "mangoes",
    "mango juice",
    "watermelon",
    "grapes",
    "grape juice",
    "cherries",
    "cherry juice",
    "fig",
    "figs",
    "dried figs",
    "fruit",
    "fruit juice",
    "fruit concentrate",
    "fruit puree",
    "fruit syrup",
    "crystalline fructose",
    "inulin",
    "oligofructose",
    "fructooligosaccharides",
    "fos",
    "chicory root",
    "jerusalem artichoke",
  ],

  histamine: [
    "histamine",
    "aged cheese",
    "old cheese",
    "mature cheese",
    "parmesan",
    "cheddar",
    "gouda",
    "blue cheese",
    "gorgonzola",
    "roquefort",
    "fermented food",
    "fermented",
    "sauerkraut",
    "kimchi",
    "kimchee",
    "pickled",
    "pickles",
    "pickled vegetables",
    "vinegar",
    "balsamic vinegar",
    "wine vinegar",
    "wine",
    "red wine",
    "white wine",
    "beer",
    "champagne",
    "sparkling wine",
    "soy sauce",
    "tamari",
    "fish sauce",
    "anchovy",
    "anchovies",
    "sardine",
    "sardines",
    "tuna",
    "canned tuna",
    "mackerel",
    "herring",
    "smoked fish",
    "dried fish",
    "salami",
    "pepperoni",
    "chorizo",
    "sausage",
    "bacon",
    "ham",
    "prosciutto",
    "salted meat",
    "smoked meat",
    "aged meat",
    "cured meat",
    "deli meat",
    "lunch meat",
    "spinach",
    "eggplant",
    "aubergine",
    "tomato",
    "tomatoes",
    "tomato paste",
    "tomato sauce",
    "ketchup",
    "catsup",
    "avocado",
    "strawberry",
    "strawberries",
    "banana",
    "bananas",
    "citrus",
    "orange",
    "lemon",
    "lime",
    "grapefruit",
    "pineapple",
    "papaya",
    "yeast extract",
    "marmite",
    "vegemite",
    "tempeh",
    "miso",
    "natto",
  ],

  nightshades: [
    "nightshade",
    "nightshades",
    "solanaceae",
    "tomato",
    "tomatoes",
    "cherry tomato",
    "roma tomato",
    "plum tomato",
    "beefsteak tomato",
    "heirloom tomato",
    "green tomato",
    "tomato paste",
    "tomato sauce",
    "tomato puree",
    "sun-dried tomato",
    "ketchup",
    "catsup",
    "marinara",
    "potato",
    "potatoes",
    "white potato",
    "red potato",
    "russet potato",
    "yukon gold",
    "fingerling potato",
    "sweet potato", // NOT a nightshade but often confused
    "french fries",
    "potato chips",
    "mashed potato",
    "potato starch",
    "potato flour",
    "eggplant",
    "aubergine",
    "brinjal",
    "pepper",
    "peppers",
    "bell pepper",
    "sweet pepper",
    "green pepper",
    "red pepper",
    "yellow pepper",
    "orange pepper",
    "chili",
    "chilli",
    "chile",
    "hot pepper",
    "cayenne",
    "cayenne pepper",
    "paprika",
    "chili powder",
    "jalapeño",
    "jalapeno",
    "habanero",
    "serrano",
    "poblano",
    "anaheim",
    "banana pepper",
    "pimento",
    "pimiento",
    "pepperoncini",
    "cherry pepper",
    "thai chili",
    "bird's eye chili",
    "scotch bonnet",
    "ghost pepper",
    "bhut jolokia",
    "carolina reaper",
    "capsicum",
    "red pepper flakes",
    "crushed red pepper",
    "goji berry",
    "goji berries",
    "wolfberry",
    "tomatillo",
    "ground cherry",
    "cape gooseberry",
    "tobacco",
    "ashwagandha",
  ],

  dairy: [
    "dairy",
    "milk",
    "cream",
    "butter",
    "buttermilk",
    "cheese",
    "yogurt",
    "yoghurt",
    "ghee",
    "whey",
    "casein",
    "caseinate",
    "lactose",
    "lactalbumin",
    "lactoglobulin",
    "curds",
    "custard",
    "pudding",
    "half and half",
    "sour cream",
    "condensed milk",
    "evaporated milk",
    "powdered milk",
    "milk powder",
    "whole milk",
    "skim milk",
    "nonfat milk",
    "low-fat milk",
    "malted milk",
    "milk solids",
    "milk protein",
    "milk fat",
    "butterfat",
    "rennet",
    "ice cream",
    "gelato",
    "sherbet",
    "kefir",
    "paneer",
    "ricotta",
    "mozzarella",
    "cheddar",
    "parmesan",
    "cottage cheese",
    "cream cheese",
    "brie",
    "camembert",
    "gouda",
    "swiss",
    "feta",
    "blue cheese",
    "frozen yogurt",
    "dairy creamer",
    "coffee creamer",
  ],
};

/**
 * Detects if any ingredients contain allergens from the user's allergen list
 * @param ingredients - Array of ingredient names to check
 * @param userAllergens - Array of user's allergens (e.g., ["peanuts", "milk"])
 * @returns Boolean indicating if any allergens were found
 */
export function hasAllergen(
  ingredients: string[],
  userAllergens: string[]
): boolean {
  if (!ingredients || !userAllergens || userAllergens.length === 0) {
    return false;
  }

  // Normalize ingredients to lowercase for case-insensitive matching
  const ingredientsLower = ingredients.map((i) => i.toLowerCase().trim());

  for (const allergen of userAllergens) {
    const allergenLower = allergen.toLowerCase().trim();

    // Skip "none" allergen
    if (allergenLower === "none" || allergenLower === "no allergies") {
      continue;
    }

    // Get keyword list for this allergen
    const keywords = allergenKeywordMapping[allergenLower] || [allergenLower];

    // Check if any ingredient contains any keyword
    for (const ingredient of ingredientsLower) {
      for (const keyword of keywords) {
        if (
          ingredient.includes(keyword.toLowerCase()) ||
          keyword.toLowerCase().includes(ingredient)
        ) {
          return true;
        }
      }
    }
  }

  return false;
}

/**
 * Gets detailed list of triggered allergens with specific ingredients
 * @param ingredients - Array of ingredient names to check
 * @param userAllergens - Array of user's allergens
 * @returns Array of triggered allergen objects with ingredient and allergen name
 */
export function getTriggeredAllergens(
  ingredients: string[],
  userAllergens: string[]
): Array<{ ingredient: string; allergen: string }> {
  if (!ingredients || !userAllergens || userAllergens.length === 0) {
    return [];
  }

  const triggered: Array<{ ingredient: string; allergen: string }> = [];
  const ingredientsLower = ingredients.map((i) => i.toLowerCase().trim());

  for (const allergen of userAllergens) {
    const allergenLower = allergen.toLowerCase().trim();

    // Skip "none" allergen
    if (allergenLower === "none" || allergenLower === "no allergies") {
      continue;
    }

    // Get keyword list for this allergen
    const keywords = allergenKeywordMapping[allergenLower] || [allergenLower];

    // Check each ingredient
    for (let i = 0; i < ingredients.length; i++) {
      const ingredient = ingredients[i];
      const ingredientLower = ingredientsLower[i];

      for (const keyword of keywords) {
        if (
          ingredientLower.includes(keyword.toLowerCase()) ||
          keyword.toLowerCase().includes(ingredientLower)
        ) {
          triggered.push({
            ingredient: ingredient, // Keep original casing
            allergen: allergen, // Keep original allergen name
          });
          break; // Only add once per ingredient
        }
      }
    }
  }

  return triggered;
}
