export const NUTRITIONIX_NUTRIENT_MAP = {
  203: { name: "Protein", unit: "g" },
  204: { name: "Total lipid (fat)", unit: "g" },
  205: { name: "Carbohydrate, by difference", unit: "g" },
  207: { name: "Ash", unit: "g" },
  208: { name: "Energy", unit: "kcal" },
  209: { name: "Starch", unit: "g" },
  210: { name: "Sucrose", unit: "g" },
  211: { name: "Glucose (dextrose)", unit: "g" },
  212: { name: "Fructose", unit: "g" },
  213: { name: "Lactose", unit: "g" },
  214: { name: "Maltose", unit: "g" },
  221: { name: "Alcohol, ethyl", unit: "g" },
  255: { name: "Water", unit: "g" },
  262: { name: "Caffeine", unit: "mg" },
  263: { name: "Theobromine", unit: "mg" },
  268: { name: "Energy", unit: "kJ" },
  269: { name: "Sugars, total", unit: "g" },
  287: { name: "Galactose", unit: "g" },
  291: { name: "Fiber, total dietary", unit: "g" },
  301: { name: "Calcium, Ca", unit: "mg" },
  303: { name: "Iron, Fe", unit: "mg" },
  304: { name: "Magnesium, Mg", unit: "mg" },
  305: { name: "Phosphorus, P", unit: "mg" },
  306: { name: "Potassium, K", unit: "mg" },
  307: { name: "Sodium, Na", unit: "mg" },
  309: { name: "Zinc, Zn", unit: "mg" },
  312: { name: "Copper, Cu", unit: "mg" },
  313: { name: "Fluoride, F", unit: "µg" },
  315: { name: "Manganese, Mn", unit: "mg" },
  317: { name: "Selenium, Se", unit: "µg" },
  318: { name: "Vitamin A, IU", unit: "IU" },
  319: { name: "Retinol", unit: "µg" },
  320: { name: "Vitamin A, RAE", unit: "µg" },
  321: { name: "Carotene, beta", unit: "µg" },
  322: { name: "Carotene, alpha", unit: "µg" },
  323: { name: "Vitamin E (alpha-tocopherol)", unit: "mg" },
  324: { name: "Vitamin D", unit: "IU" },
  325: { name: "Vitamin D2 (ergocalciferol)", unit: "µg" },
  326: { name: "Vitamin D3 (cholecalciferol)", unit: "µg" },
  328: { name: "Vitamin D (D2 + D3)", unit: "µg" },
  334: { name: "Cryptoxanthin, beta", unit: "µg" },
  337: { name: "Lycopene", unit: "µg" },
  338: { name: "Lutein + zeaxanthin", unit: "µg" },
  341: { name: "Tocopherol, beta", unit: "mg" },
  342: { name: "Tocopherol, gamma", unit: "mg" },
  343: { name: "Tocopherol, delta", unit: "mg" },
  344: { name: "Tocotrienol, alpha", unit: "mg" },
  345: { name: "Tocotrienol, beta", unit: "mg" },
  346: { name: "Tocotrienol, gamma", unit: "mg" },
  347: { name: "Tocotrienol,delta", unit: "mg" },
  401: { name: "Vitamin C, total ascorbic acid", unit: "mg" },
  404: { name: "Thiamin", unit: "mg" },
  405: { name: "Riboflavin", unit: "mg" },
  406: { name: "Niacin", unit: "mg" },
  410: { name: "Pantothenic acid", unit: "mg" },
  415: { name: "Vitamin B-6", unit: "mg" },
  417: { name: "Folate, total", unit: "µg" },
  418: { name: "Vitamin B-12", unit: "µg" },
  421: { name: "Choline, total", unit: "mg" },
  428: { name: "Menaquinone-4", unit: "µg" },
  429: { name: "Dihydrophylloquinone", unit: "µg" },
  430: { name: "Vitamin K (phylloquinone)", unit: "µg" },
  431: { name: "Folic acid", unit: "µg" },
  432: { name: "Folate, food", unit: "µg" },
  435: { name: "Folate, DFE", unit: "µg" },
  454: { name: "Betaine", unit: "mg" },
  501: { name: "Tryptophan", unit: "g" },
  502: { name: "Threonine", unit: "g" },
  503: { name: "Isoleucine", unit: "g" },
  504: { name: "Leucine", unit: "g" },
  505: { name: "Lysine", unit: "g" },
  506: { name: "Methionine", unit: "g" },
  507: { name: "Cystine", unit: "g" },
  508: { name: "Phenylalanine", unit: "g" },
  509: { name: "Tyrosine", unit: "g" },
  510: { name: "Valine", unit: "g" },
  511: { name: "Arginine", unit: "g" },
  512: { name: "Histidine", unit: "g" },
  513: { name: "Alanine", unit: "g" },
  514: { name: "Aspartic acid", unit: "g" },
  515: { name: "Glutamic acid", unit: "g" },
  516: { name: "Glycine", unit: "g" },
  517: { name: "Proline", unit: "g" },
  518: { name: "Serine", unit: "g" },
  521: { name: "Hydroxyproline", unit: "g" },
  539: { name: "Sugars, added", unit: "g" },
  601: { name: "Cholesterol", unit: "mg" },
  605: { name: "Fatty acids, total trans", unit: "g" },
  606: { name: "Fatty acids, total saturated", unit: "g" },
  607: { name: "Fatty acid 4:0", unit: "g" },
  608: { name: "Fatty acid 6:0", unit: "g" },
  609: { name: "Fatty acid 8:0", unit: "g" },
  610: { name: "Fatty acid 10:0", unit: "g" },
  611: { name: "Fatty acid 12:0", unit: "g" },
  612: { name: "Fatty acid 14:0", unit: "g" },
  613: { name: "Fatty acid 16:0", unit: "g" },
  614: { name: "Fatty acid 18:0", unit: "g" },
  615: { name: "Fatty acid 20:0", unit: "g" },
  617: { name: "Fatty acid 18:1 undifferentiated", unit: "g" },
  618: { name: "Fatty acid 18:2 undifferentiated", unit: "g" },
  619: { name: "Fatty acid 18:3 undifferentiated", unit: "g" },
  620: { name: "Fatty acid 20:4 undifferentiated", unit: "g" },
  621: { name: "Fatty acid 22:6 n-3 (DHA)", unit: "g" },
  624: { name: "Fatty acid 22:0", unit: "g" },
  625: { name: "Fatty acid 14:1", unit: "g" },
  626: { name: "Fatty acid 16:1 undifferentiated", unit: "g" },
  627: { name: "Fatty acid 18:4", unit: "g" },
  628: { name: "Fatty acid 20:1", unit: "g" },
  629: { name: "Fatty acid 20:5 n-3 (EPA)", unit: "g" },
  630: { name: "Fatty acid 22:1 undifferentiated", unit: "g" },
  631: { name: "Fatty acid 22:5 n-3 (DPA)", unit: "g" },
  636: { name: "Phytosterols", unit: "mg" },
  638: { name: "Stigmasterol", unit: "mg" },
  639: { name: "Campesterol", unit: "mg" },
  641: { name: "Beta-sitosterol", unit: "mg" },
  645: { name: "Fatty acids, total monounsaturated", unit: "g" },
  646: { name: "Fatty acids, total polyunsaturated", unit: "g" },
  652: { name: "Fatty acid 15:0", unit: "g" },
  653: { name: "Fatty acid 17:0", unit: "g" },
  654: { name: "Fatty acid 24:0", unit: "g" },
  662: { name: "Fatty acid 16:1 t", unit: "g" },
  663: { name: "Fatty acid 18:1 t", unit: "g" },
  669: { name: "Fatty acid 18:2 t,t", unit: "g" },
  670: { name: "Fatty acid 18:2 CLAs", unit: "g" },
  671: { name: "Fatty acid 24:1 c", unit: "g" },
  672: { name: "Fatty acid 20:2 n-6 c,c", unit: "g" },
  673: { name: "Fatty acid 16:1 c", unit: "g" },
  674: { name: "Fatty acid 18:1 c", unit: "g" },
  675: { name: "Fatty acid 18:2 n-6 c,c", unit: "g" },
  685: { name: "Fatty acid 18:3 n-6 c,c,c", unit: "g" },
  687: { name: "Fatty acid 17:1", unit: "g" },
  689: { name: "Fatty acid 20:3 undifferentiated", unit: "g" },
  693: { name: "Fatty acids, total trans-monoenoic", unit: "g" },
  695: { name: "Fatty acids, total trans-polyenoic", unit: "g" },
  696: { name: "Fatty acid 13:0", unit: "g" },
  697: { name: "Fatty acid 15:1", unit: "g" },
  851: { name: "Fatty acid 18:3 n-3 c,c,c (ALA)", unit: "g" },
  852: { name: "Fatty acid 20:3 n-3", unit: "g" },
  853: { name: "Fatty acid 20:3 n-6", unit: "g" },
  855: { name: "Fatty acid 20:4 n-6", unit: "g" },
  857: { name: "Fatty acid 21:5", unit: "g" },
  858: { name: "Fatty acid 22:4", unit: "g" },
  859: { name: "Fatty acid 18:1-11t (18:1t n-7)", unit: "g" },
};
